apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-k8s-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: diplom-k8s-app
  template:
    metadata:
      labels:
        app: diplom-k8s-app
    spec:
      containers:
        - name: diplom-k8s-app
          image: aleksandrzol/diplom-k8s-app:1.0.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP